---
title: "Untitled"
output: html_document
---



```{r}
library(ggplot2)

countries = c('Australia', 'Central Asia', "East South America", 'Europe', 'Horn of Africa', 'Middle East', 'North America', 'Northern Africa', 'Sahel', 'South West Asia', 'Southern Africa', 'West South America')
# Proposed
correlations = c(0.69, 0.80, 0.83, 0.78, 0.87, 0.83, 0.73, 0.96, 0.8, 0.71, 0.62, 0.8)
lower_ci = c(0.52, 0.41, 0.63, 0.62, 0.8, 0.62, 0.53, 0.88, 0.69, 0.55, 0.44, 0.65)
upper_ci = c(0.83, 0.99, 0.95, 0.89, 0.94, 0.98, 0.88, 1.0, 0.88, 0.96, 0.86, 0.89)
df_proposed = data.frame("Countries" = countries, "Correlations" = correlations, "Lower" = lower_ci, "Upper" = upper_ci, "Model" = "Proposed")

# Random Forest
correlations = c(0.42, 0.92, 0.74, 0.77, 0.80, 0.93, 0.68, 0.87, 0.68, 0.63, 0.4, 0.82)
lower_ci = c(0.11, 0.69, 0.45, 0.63, 0.65, 0.86, 0.5, 0.66, 0.53, 0.46, 0.22, 0.73)
upper_ci = c(0.68, 0.97, 0.91, 0.88, 0.88, 0.97, 0.84, 1.0, 0.79, 0.82, 0.56, 0.91)
df_rf = data.frame("Countries" = countries, "Correlations" = correlations, "Lower" = lower_ci, "Upper" = upper_ci, "Model" = "Random Forest")

df = rbind(df_proposed, df_rf)
```

```{r}

pl0 = ggplot(data = df, aes(x = Countries, y = Correlations, fill=Model))+
  geom_bar(position = position_dodge(), stat = "identity")+
  coord_flip()+theme_bw()+ylab("Pearson correlation")+
  geom_errorbar(aes(ymin=Lower, ymax = Upper), position = position_dodge(width=0.9), width = 0.2)+
  xlab("")

pl1 = ggplot(data = df_proposed, aes(x = countries, y = Correlations))+
  geom_col()+coord_flip()+theme_bw()+ylab("Pearson correlation")+
  geom_errorbar(aes(ymin=Lower, ymax = Upper), width = 0.2)+
  xlab("")

pl2 = ggplot(data = df_rf, aes(x = countries, y = Correlations))+
  geom_col()+coord_flip()+theme_bw()+ylab("Pearson correlation")+
  geom_errorbar(aes(ymin=Lower, ymax = Upper), width = 0.2)+
  xlab("")

print(pl0)
```
```{r}
print(pl1)
```
```{r}
library(ggplot2)

countries = c('Africa', 'Asia', 'Australia', 'Europe', 'North America', 'South America')
# Proposed
correlations = c(0.86, 0.85, 0.76, 0.82, 0.77, 0.90)
upper_ci = c(0.88, 0.88, 0.81, 0.85, 0.81, 0.92)
lower_ci = c(0.83, 0.82, 0.69, 0.78, 0.72, 0.88)
df_proposed = data.frame("Countries" = countries, "Correlations" = correlations, "Lower" = lower_ci, "Upper" = upper_ci, "Model" = "Proposed")

# Random Forest
correlations = c(0.71, 0.87, 0.59, 0.76, 0.64, 0.89)
lower_ci = c(0.64, 0.82, 0.45, 0.69, 0.54, 0.85)
upper_ci = c(0.76, 0.9, 0.71, 0.81, 0.72, 0.92)
df_rf = data.frame("Countries" = countries, "Correlations" = correlations, "Lower" = lower_ci, "Upper" = upper_ci, "Model" = "Random Forest")

correlations = c(0.78, 0.81, 0.71, 0.66, 0.62, 0.85)
lower_ci = c(0.73, 0.75, 0.61, 0.57, 0.52, 0.79)
upper_ci = c(0.82, 0.86, 0.80, 0.74, 0.70, 0.887)
df_unet = data.frame("Countries" = countries, "Correlations" = correlations, "Lower" = lower_ci, "Upper" = upper_ci, "Model" = "U-Net")

df = rbind(df_proposed, df_rf, df_unet)

library(scales)
ggplot(data = df, aes(x = Countries, y = Correlations, fill=Model))+
  geom_bar(position = position_dodge(), stat = "identity")+
  theme_bw()+ylab("Pearson correlation")+
  geom_errorbar(aes(ymin=Lower, ymax = Upper), stat = "identity", position = position_dodge(width=.9), width = 0.2)+
  xlab("")+
  scale_y_continuous(limits=c(0.4,1),oob = rescale_none)+
  scale_fill_brewer(type = 'qual')
```

```{r}
library(dplyr)
library(tidyr)
library(rgdal)
library(sp)
library(sf)
library(ggplot2)
library(rgeos)
library(broom)
library(mapproj)
```

```{r}
geojson = "../../references/json/land.geojson"
input.proj <- CRS("+proj=longlat + datum=WGS84")
map <- readOGR(geojson)
map.df <- fortify(map)
```


```{r, fig.width=11, fig.height=7}
library(ggalt)
fao_data = read.csv("../../data/drylands/latlong.csv")

bastin <- ggplot()+
  geom_polygon(data = map.df, aes(x = long, y = lat, group = group), fill = "white", colour = "black", size = 0.1)+
  geom_point(data = fao_data, aes(x = longs, y = lats), color = "blue4", size = 0.25)+
  #ylim(-54, 85)+
  #xlim(-173, 180)+
  theme_bw()+
  ggtitle("Global tree cover plots from Bastin et al. 2017")+
  xlab("")+
  ylab("")+
  coord_proj("+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs",
             xlim=c(-130, 167),
             ylim=c(-58, 80))+
  theme(plot.margin=unit(c(0,0,0,0),"cm"))

ggsave("../../references/pdf/bastin.pdf", bastin, "pdf", width = 8.75, height = 4.5, units = "in")
#print(bastin)
```

```{r, fig.width=11, fig.height=7}
library(ggalt)
training_data = read.csv("../../data/latlongs/training.csv")

training_plots = ggplot()+
  geom_polygon(data = map.df, aes(x = long, y = lat, group = group), fill = "white", colour = "black", size = 0.1)+
  geom_point(data = training_data, aes(x = longs, y = lats), color = "red", size = 0.25)+
  #ylim(-54, 85)+
  #xlim(-173, 180)+
  theme_bw(base_size = 12)+
  ggtitle("Training plots")+
  xlab("")+
  ylab("")+
  coord_proj("+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs",
             xlim=c(-130, 167),
             ylim=c(-58, 80))+
  theme(plot.margin=unit(c(0,0,0,0),"cm"))#+
  #scalebar(location = "bottomleft", transform = TRUE, dist = 2000, model = "WGS84", dist_unit = "km", x.min = -130, x.max = 167, y.min = -58, y.max = 80, st.bottom = TRUE)

#ggsave("../../references/pdf/train-plots.pdf", training_plots, "pdf", width = 8.6, height = 4.5, units = "in")
```

# New training samples 
```{r}
library(ggalt)
training_data = read.csv("../../data/latlongs/training.csv")
new_data = read.csv("../../data/latlongs/new_sa_samples.csv")

geojson = "../../references/json/custom.geo.json"
map <- readOGR(geojson)
map.df <- fortify(map)

training_plots = ggplot()+
  geom_polygon(data = map.df, aes(x = long, y = lat, group = group), fill = "white", colour = "black", size = 0.1)+
  geom_point(data = new_data, aes(x = longs, y = lats), color = "blue", size = 0.2)+
  geom_point(data = training_data, aes(x = longs, y = lats), color = "red", size = 0.2)+
  #ylim(-54, 85)+
  #xlim(-173, 180)+
  theme_bw(base_size = 12)+
  ggtitle("Training plots")+
  xlab("")+
  ylab("")+
  coord_proj("+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs",
             xlim=c(-100, -80), # -100, -35, -40, 25
             ylim=c(0, 25))+
  theme(plot.margin=unit(c(0,0,0,0),"cm"))

print(training_plots)
```


```{r, fig.width=11, fig.height=7}
library(ggalt)
testing_data = read.csv("../../data/latlongs/testing_plots.csv")

testing_plots = ggplot()+
  geom_polygon(data = map.df, aes(x = long, y = lat, group = group), fill = "white", colour = "black", size = 0.1)+
  #ylim(-54, 85)+
  #xlim(-173, 180)+
  geom_point(data = testing_data, aes(x = longs, y = lats), color = "blue3", size = 0.25)+
  theme_bw(base_size = 9)+
  xlab("")+
  ylab("")+
  ggtitle("Testing plots - global pixel accuracy")+
  coord_proj("+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs",
             xlim=c(-130, 167),
             ylim=c(-58, 80))+
  theme(plot.margin=unit(c(0,0,0,0),"cm"))

#ggsave("../../references/pdf/test-plots.pdf", testing_plots, "pdf", width = 9.3, height = #4.5, units = "in")
```

```{r}
library(ggalt)
geojson = "../../references/json/custom.geo.json"
map <- readOGR(geojson)
map.df <- fortify(map)

data = read.csv("../../data/latlongs/landscapes.csv")

 ggplot()+
  geom_polygon(data = map.df, aes(x = long, y = lat, group = group), fill = "white", colour = "black", size = 0.1)+
  #ylim(-54, 85)+
  #xlim(-173, 180)+
  geom_point(data = data, aes(x = longitude, y = latitude), color = "blue3", size = 1.3)+
  theme_bw(base_size = 9)+
  xlab("")+
  ylab("")+
  coord_proj("+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs",
             xlim=c(-130, 167),
             ylim=c(-58, 80))+
  theme(plot.margin=unit(c(0,0,0,0),"cm"))+
  ggtitle("Landscape locations")

```


```{r, fig.width=5, fig.height=5}}
library(ggsn)
#geojson = "../../references/json/custom.geo.json"
#map <- readOGR(geojson)
#map.df <- fortify(map)
# Honduras
y <- seq(14.1, 15.1, 0.1)  #(6, 20)
x <- seq(-88.7, -87.7, 0.1) #(-90, -80)

# Ghana
y <- seq(7.4, 8.4, 0.1) #(-5, 5)
x <- seq(-1.2, -0.2, 0.1) #(-2, 12)

# Tanzania
#x <- seq(36.7, 37.7, 0.1) # 30, 40
#y <- seq(-6.2, -5.2, 0.1) @ -10, 4

grid <- expand.grid(x,y)
grid$latlong <- paste(grid$Var2, grid$Var1)
local = ggplot()+
  geom_polygon(data = map.df, aes(x = long, y = lat, group = group), fill = "white", colour = "black", size = 0.2)+
  geom_point(data = grid, aes(x = Var1, y = Var2), color = "blue3", size = 0.05)+
  coord_cartesian(ylim = c(-2, 12), xlim = c(-5, 5))+
  scalebar(transform = TRUE, dist = 200, model = "WGS84", dist_unit = "km", location = "bottomleft", x.min = -5, x.max = 5, y.min = -2, y.max = 12, st.bottom = FALSE)+
  theme_bw()+
  ggtitle("Ghana")+
  xlab("")+
  ylab("")

print(local)
```

```{r}
library(grid)
library(ggmap)

main +
    inset(ggplotGrob(honduras), xmin = -76.7, xmax = 0, ymin = 20, ymax = 50)
```

```{r}
library(ggalt)
library(plyr)
geojson = "../../references/json/custom.geo.json"
mapa <- readOGR(geojson)
mapa@data$id <- rownames(mapa@data)
mapa@data   <- join(mapa@data, data)
mapa.df     <- fortify(mapa)
mapa.df     <- join(mapa.df,mapa@data, by="id")

mapa.df$name_long = as.character(mapa.df$name_long)
mapa.df$name_long[mapa.df$name_long == 'Russian Federation'] = 'Russia'
mapa.df$name_long[mapa.df$name_long == "Côte d'Ivoire"]  = 'Ivory Coast'
mapa.df$name_long[mapa.df$name_long == 'Republic of Congo'] = 'Democratic Republic of the Congo'
mapa.df$name_long[mapa.df$name_long == 'Lao PDR'] = 'Laos'
mapa.df$name_long[mapa.df$name_long == 'Bosnia and Herzegovina']  = 'Bosnia-Herzegovina'
mapa.df$name_long[mapa.df$name_long == 'Slovakia']  = 'Slovak Republic'
mapa.df$name_long[mapa.df$name_long == 'Republic of Korea']  = 'South Korea'
mapa.df$name_long[mapa.df$name_long == 'Dem. Rep. Korea']  = 'North Korea'
```

```{r}
gdelt_data = read.table("../../references/gdelt-data.txt", sep = '\t' )
colnames(gdelt_data) = c("source", "code", "country")
gdelt_summarized = gdelt_data %>% dplyr::group_by(country) %>% dplyr::summarize(n = dplyr::n())
colnames(gdelt_summarized) = c('name_long', 'count')
gdelt_summarized = plyr::join(gdelt_summarized, mapa.df, by = 'name_long', type = 'full')
```

```{r}
my_breaks <- round_any(exp(seq(log(10), log(10000), length = 7)), 5)
my_breaks = c(5, 25, 125,  625, 3125, 15625)
pl = ggplot()+
  geom_polygon(data = gdelt_summarized, aes(x = long, y = lat, group = group, fill = count), colour = "black", size = 0.1)+
  #ylim(-54, 85)+
  #xlim(-173, 180)+
  theme_bw(base_size = 9)+
  xlab("")+
  ylab("")+
  scale_fill_gradient(name = "Count", trans = "log", breaks = my_breaks, labels = my_breaks)+
  coord_proj("+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs",
             xlim=c(-130, 167),
             ylim=c(-58, 80))+
  theme(plot.margin=unit(c(0,0,0,0),"cm"))+
  ggtitle("GDELT sources by country")

print(pl)
```

